<?php

namespace CitasBundle\Repository;

/**
 * ConsultoriosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultoriosRepository extends \Doctrine\ORM\EntityRepository
{
}
