<?php

namespace CitasBundle\Repository;

/**
 * EpsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpsRepository extends \Doctrine\ORM\EntityRepository
{
}
