<?php

namespace CitasBundle\Repository;

/**
 * PacienteNotasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteNotasRepository extends \Doctrine\ORM\EntityRepository
{
}
